// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: gh_search/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GithubSearchService_Search_FullMethodName = "/gh_search.v1.GithubSearchService/Search"
)

// GithubSearchServiceClient is the client API for GithubSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GithubSearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type githubSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGithubSearchServiceClient(cc grpc.ClientConnInterface) GithubSearchServiceClient {
	return &githubSearchServiceClient{cc}
}

func (c *githubSearchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, GithubSearchService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubSearchServiceServer is the server API for GithubSearchService service.
// All implementations must embed UnimplementedGithubSearchServiceServer
// for forward compatibility.
type GithubSearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedGithubSearchServiceServer()
}

// UnimplementedGithubSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGithubSearchServiceServer struct{}

func (UnimplementedGithubSearchServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedGithubSearchServiceServer) mustEmbedUnimplementedGithubSearchServiceServer() {}
func (UnimplementedGithubSearchServiceServer) testEmbeddedByValue()                             {}

// UnsafeGithubSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GithubSearchServiceServer will
// result in compilation errors.
type UnsafeGithubSearchServiceServer interface {
	mustEmbedUnimplementedGithubSearchServiceServer()
}

func RegisterGithubSearchServiceServer(s grpc.ServiceRegistrar, srv GithubSearchServiceServer) {
	// If the following call pancis, it indicates UnimplementedGithubSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GithubSearchService_ServiceDesc, srv)
}

func _GithubSearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubSearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GithubSearchService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubSearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GithubSearchService_ServiceDesc is the grpc.ServiceDesc for GithubSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GithubSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gh_search.v1.GithubSearchService",
	HandlerType: (*GithubSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _GithubSearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gh_search/v1/service.proto",
}
