name: Continuous Integration

on:
  push:
    branches:
      - '**'

jobs:
  lint-test-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - name: Set up make
        run: sudo apt-get install -y make
      - name: Set up tools
        run: |
          sudo apt-get install -y protobuf-compiler
          make setup-tools
          echo "${GOPATH}/bin" >> $GITHUB_PATH
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: compile
        run: make compile
      - name: compile-client
        run: make compile-client

